api/urls.py
from django.urls import path

from . import views


app_name = 'api'
urlpatterns = [
    path('todo/list/', views.ApiTodoLV.as_view(), name='list'),
    path('todo/<int:pk>/delete/', views.ApiTodoDelV.as_view(), name='delete'),
    path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path('', views.TodoTV.as_view(), name='index'),
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models


# Create your models here.
class Todo(models.Model):
    name = models.CharField('NAME', max_length=10, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.name:
            self.name = "홍길동"
        super().save()

api/views.py
from django.forms import model_to_dict
from django.http import JsonResponse
from django.utils.decorators import method_decorator
# from django.views.decorators.csrf import csrf_exempt
# from django.views.generic import ListView, DeleteView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic.edit import BaseDeleteView, BaseCreateView
from django.views.generic.list import BaseListView

from todo.models import Todo
import json


# Create your views here.
@method_decorator(ensure_csrf_cookie, name='dispatch')
class ApiTodoLV(BaseListView):
    model = Todo
    # template_name =

    # def get(self, request, *args, **kwargs):
    #     tmpList = [
    #         {"id": 1, "name": 'djuhoi', "todo": '11111'},
    #         {"id": 2, "name": 'ddjango', "todo": '22222'},
    #         {"id": 3, "name": 'd김주회', "todo": '33333'},
    #         {"id": 4, "name": 'd장고', "todo": '44444'},
    #     ]
    #
    #     return JsonResponse(data=tmpList, safe=False)

    def render_to_response(self, context, **response_kwargs):
        todoList = list(context['object_list'].values())

        return JsonResponse(data=todoList, safe=False)


# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoDelV(BaseDeleteView):
    model = Todo

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return JsonResponse(data={}, status=204)


# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = '__all__'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body)
        return kwargs

    def form_valid(self, form):
        print("form_valid()", form)
        self.object = form.save()
        newTodo = model_to_dict(self.object)
        print(f"newTodo: {newTodo}")
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        print("form_invalid()", form)
        return JsonResponse(data=form.errors, status=400)

mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.views.generic import TemplateView


class TodoTV(TemplateView):
    template_name = 'todo/todo_index.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>
<body style="padding-top: 90px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'home' %}">Blog(tobe)</a>
      </li>

      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Util
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul>

    <form class="form-inline my-2">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
    </form>

    <ul class="navbar-nav ml-5 mr-5">
      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
          <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;
        </a>
        <div class="dropdown-menu">
          <a href="{% url 'home' %}" class="dropdown-item">Login</a>
          <a href="{% url 'home' %}" class="dropdown-item">Register</a>
        </div>
      </li>
    </ul>

  </div>
</nav>

<div class="container">
  {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/0a42d77ee4.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

templates/todo/todo_index.html
{% extends 'base.html' %}

{% block title %} Vue Django Todo Application {% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover {
            color: red;
        }
        [v-clock] {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app" v-cloak>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>
        <br>

        <div class="inputBox">
            <input class="name" type="text" placeholder="name ..." v-model.trim="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="todo" @keyup.enter="add_todo">
            <button @click="add_todo" class="btn btn-primary btn-sm">ADD</button>
        </div>

        <ul class="todoList">
            <li v-for="(todo, index) in todoList">
                <span>[[ todo.name ]]::: [[ todo.todo ]]</span>
                <span class="removeBtn" @click="remove_todo(todo, index)">X</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block extra-script %}
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = 'X-CSRFToken';

        var vm = new Vue({
            delimiters: ['[[', ']]'],
            el: '#app',
            data: {
                name: '',
                todo: '',
                todoList:[],
            },
            created: function() {
                console.log("created()...");
                this.fetch_all_todo();
            },
            methods: {
                fetch_all_todo: function() {
                    console.log("fetch_all_todo()...");

                    var that = this;
                    axios.get('/api/todo/list/')
                        .then(function (res) {
                            console.log("GET RES", res);
                            that.todoList = res.data;
                        })
                        .catch(function (err) {
                            console.log("GET ERR", err);
                        })
                },
                add_todo: function() {
                    console.log("add_todo()...");
                    if (this.todo == '') return;
                    if (this.name == '') this.name = "김주회";

                    var postData = {name: this.name, todo: this.todo};
                    var that = this;
                    axios.post('/api/todo/create/', postData)
                        .then(function (res) {
                            console.log("POST RES ", res);
                            that.todoList.push({name: res.data.name, todo: res.data.todo});
                            that.clear_input();
                        })
                        .catch(function (err) {
                            console.log("POST ERR ", err);
                        })
                },
                remove_todo: function(todo, index) {
                    console.log("remove_todo()... ", index);
                    if (confirm("Really delete ?")==false) return;

                    var that = this;
                    axios.delete('/api/todo/' + todo.id + '/delete/')
                        .then(function (res) {
                            console.log("DELETE RES ", res);
                            that.todoList.splice(index, 1);
                        })
                        .catch(function (err) {
                            console.log("DELETE ERR ", err);
                        })
                },
                clear_input: function() {
                    this.name = '';
                    this.todo = '';
                }
            },
        })
    </script>
{% endblock %}